
server:
  port: 9001
spring:
  application:
    name: xuetang
  devtools:
    restart:
    enabled: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
mybatis:
  typeAliasesPackage: com.cn.xuetang.po
  mapper-locations: classpath:mapper/*Mapper.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
 